config/routes.rb
Rails.application.routes.draw do
  root "home#show", page: "home"

  get "/home/:page", to: "home#show"

  get "/listings/mylistings", to: "listings#mylistings"

  resources :users
  resources :listings

  get "/sign_in", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy"

  
  post "/listings/searchresults", to: "listings#searchresults"

  get "/search", to: "search#index"
  get "/search/show", to: "search#show"

  get "*path", to: "home#show", page: "home"

end 

app/models/listing.rb
class Listing < ActiveRecord::Base
	belongs_to :user

	has_attached_file :avatar, 
					styles: { medium: "300x300>", thumb: "100x100>" }, 
					default_url: "/images/:style/missing_listing_avatar.png",
					storage: :s3,
					bucket: ENV['S3_BUCKET_NAME'],
					s3_credentials: {access_key_id: ENV["AWS_ACCESS_KEY_ID"], secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"]}
	# has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing_listing_avatar.png"
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

	def self.produce_categories
		[:Apples,
		 :Artichokes,
		 :Asparagus,
		 :Avocados,
		 :Bananas,
		 :Beets,
		 :Berries,
		 "Broccoli/Cauliflower",
		 "Brussel Sprouts",
		 :Carrots,
		 :Celery,
		 :Cherries,
		 :Chilis,
		 "Citrus Fruits",
		 :Corn,
		 :Cucumber,
		 :Dates,
		 :Eggplant,
		 :Gourds,
		 :Grapes,
		 "Leafy Greens",
		 :Lettuce,
		 :Melons,
		 :Mushrooms,
		 :Onions,
		 "Other Fruits",
		 "Other Vegetables",
		 :Pears,
		 :Peppers,
		 :Potatoes,
		 "Seasonal Vegetables",
		 :Sprouts,
		 "Stone Fruits",
		 :Strawberries,
		 :Tomatoes,
		 "Tropical Fruits",
		 :Zucchini]
	end
end


		# <% @cities.each do |city| %>
		# 	<%= city %>
		# <% end %>

app/models/user.rb
class User < ActiveRecord::Base
has_attached_file :avatar, 
					styles: { medium: "300x300>", thumb: "100x100>" }, 
					default_url: "/images/:style/missing_profile_avatar.png",
					storage: :s3,
					bucket: ENV['S3_BUCKET_NAME'],
					s3_credentials: {access_key_id: ENV["AWS_ACCESS_KEY_ID"], secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"]}

validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

has_many :listings, dependent: :destroy

has_secure_password
validates 	:email, uniqueness: true
validates :username, uniqueness: true



	def self.confirm(params)
		@user = User.find_by({email: params[:email]})
		@user.try(:authenticate, params[:password])
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper


  private
  	def require_login
		if !current_user
  			redirect_to "/sign_in"
  		end
  	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def show
		@current_user
		@logged_in
		render template: "home/#{params[:page]}"
	end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
before_action :require_login

	def index
		@listings = Listing.all
		render :index
	end

	def mylistings
		@listing = Listing.all
		render :mylistings
	end

	def new
		@listing = Listing.new
		render :new
	end

	def create
		@listing = Listing.create(listing_params)
		redirect_to "/listings/#{@listing.id}"
	end

	def show
		@listing = Listing.find(params[:id])
		render :show
	end

	def edit
		@listing = Listing.find(params[:id])
		if (@current_user == @listing.user)
			render :edit
		else
			redirect_to "/"
			end
	end

	def update
		listing = Listing.find(params[:id])
		listing.update_attributes(listing_params)
		redirect_to listing
	end

	def destroy
		listing = Listing.find(params[:id])
		listing.destroy
		redirect_to "/users/#{@current_user.id}"
	end


private
	def listing_params
		params.require(:listing).permit(:produce_category, :title, :quantity, :description, :address_line1, :address_line2, :city, :state, :zip, :phone, :prefers_phone, :prefers_email, :user_id, :avatar)
	end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	before_action :require_login
	def index
		search_term = {}
		if params[:Cities].nil? || params[:Category].nil?
			params[:Cities] = ""
			params[:Category] = ""
		end
		search_term[:city] = params[:Cities] unless params[:Cities].empty?
		search_term[:produce_category] = params[:Category] unless params[:Category].empty?
		@listings = Listing.where(search_term)
		@cities = Listing.uniq.pluck(:city)
		@produce_categories = Listing.uniq.pluck(:produce_category)
		render layout: "search_listings"
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		@user = User.new
		redirect_to current_user if current_user
	end

	def create
		user_params = params.require(:user).permit(:email, :password)
		@user = User.confirm(user_params)
		if @user
			login(@user)
			redirect_to "/users/#{@user.id}"
		else
			flash[:error] = "Failed To Authenticate. Please try again."
			redirect_to "/sign_in"
		end
	end

	def destroy
		session.delete(:user_id)
		redirect_to "/"
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :require_login, only: [:index, :show, :edit, :update, :destroy]

	def index
		@users = User.all
		render :index
	end

	def new
		current_user
		logged_in?
		if (@logged_in == false)
			@user = User.new
			render :new
		else
			redirect_to "/users/#{@current_user.id}"
		end
	end

	def create
		@user = User.create(user_params)
		login(@user)
		redirect_to "/users/#{@user.id}"
	end

	def show
		@user = User.find(params[:id])
		render :show
	end

	def edit
		@user = User.find(params[:id])
		authorize
			if (@right_person)
				render :edit
			else
				redirect_to "/"
			end
	end

	def update
		user = User.find(params[:id])
		user.update_attributes(user_params)
		redirect_to user
	end

	def destroy
		user = User.find(params[:id])
		logout
		user.destroy
		redirect_to "/"
	end

private
	def user_params
		params.require(:user).permit(:username, :email, :password, :avatar)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def login(user)
		session[:user_id] = user.id
		@current_user = user
		@logged_in = true
	end

	def current_user
		@current_user ||= session[:user_id] && User.find(session[:user_id])
	end

	def logged_in?
		if @current_user == nil
	  		@logged_in = false
	  	else
	  		@logged_in = true
		end
	end

	def logout
		@current_user = session[:user_id] = nil
	end

	def authorize
		if @current_user == User.find(params[:id])
			@right_person = true
		else 
			@right_person = false
		end
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_loggedin_navbar.html.erb
<nav class="navbar navbar-default" id="transparent">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
	<%= link_to "Love at First Bite", "/", method: "get", class: "navbar-brand" %>
	<% if @current_user%>
		<span class="navbar-brand" id="greeting">Welcome, <%= @current_user.username %>
		</span>
	<% end %>
	</div>

    <div class="collapse navbar-collapse" id="my_nav">
      <ul class="nav navbar-nav navbar-right">
		<li><%= link_to "About", "/home/about", method: "get"%></li>
		<li><%= link_to "FAQ", "/home/faq", method: "get" %></li>
		<li><%= link_to "Browse Produce Listings", "/search", method: "get" %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Profile <span class="caret"></span></a>
          <ul class="dropdown-menu dropdown-menu-left">
			<li><%= link_to "View My Profile", "/users/#{@current_user.id}", method: "get" %></li>
			<li><%= link_to "Manage My Listings", "/listings/mylistings", method: "get" %></li>
			<li><%= link_to "Edit My Profile", "/users/#{@current_user.id}/edit", method: "get" %></li>
          </ul>
        </li>
        <li><%= link_to "Sign Out", "/sessions", method: "delete" %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/application/_loggedout_navbar.html.erb
<nav class="navbar navbar-default" id="transparent">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Love at First Bite</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="/home/about">About</a></li>
      <li><a href="/home/faq">FAQ</a></li>
      <li><a href="/sign_in">Sign In</a></li> 
    </ul>
  </div>
</nav>

app/views/application/_sidebar.html.erb
<div class="sidebar col-md-4">
	  <%= form_tag(search_path, :method => "get") do %>
		<div class="sidebar-search-by-city">
			<p class="instructional-text-lg">Search by City</p>
			<%= select_tag "Cities", options_for_select(@cities.sort), include_blank: "All" %>
		</div>
		<br>
		<div class="sidebar-search-by-produce-category">	
			<p class="instructional-text-lg">Search by Category</p>
			<%= select_tag "Category", options_for_select(@produce_categories.sort), include_blank: "All"  %>
		</div>
		<br>
	<%= button_to "Search", "/search/show", method: "get", class: "btn btn-default btn-lg" %>
	<% end %>
</div>

app/views/home/about.html.erb
<div id="about-page-div">
	<h1 class="jumbo-header"><b>Did you know?</b></h1>
	<div class="about-blurbs-div header-text-sm"
	<ul id="about-blurbs-ul">
	<li class="food-fact">Getting food to our tables eats up <b>10%</b> of the total U.S. energy budget, uses <b>50%</b> of U.S. land,and swallows <b>80%</b> of freshwater consumed in the United States.</li>
	<li class="food-fact">Yet in the U.S., <b>20 lb.</b> of edible food per person, per month goes uneaten.</li>
	<li class="food-fact">Moreover, almost all of that uneaten food ends up rotting in landfills where organic matter accounts for <b>16%</b> of U.S. methane emissions.</li>
	<li class="food-fact">And while <b>1 in 6</b> people in America face hunger...</li>
	<li class="food-fact header-text-md"><b>20% of the produce grown in the U.S. is rejected from grocery stores because it has a funny shape or size.</b></li>
	</ul>
	</div>
</div>
<%= image_tag "rowfruit1.png", :class => "bottom-row-image" %>
<!-- <img src="/assets/rowfruit1.png" class="bottom-row-image"> -->

app/views/home/faq.html.erb
<div id="faq-page-div">
	<h1 class="jumbo-header"><b>FAQ</b></h1>
	<ul id="faq-ul">
		<li class="faq-question header-text-sm">
		How do I search for produce in my area?
		</li>
		<li class="faq-answer instructional-text-lg">Sign up as a user to begin browsing produce listings in minutes! Once you create a profile and log in, you can search produce listings by owner username, city, and category of produce.
		</li>
		<li class="faq-question header-text-sm">
		How do I create a produce listing?
		</li>
		<li class="faq-answer instructional-text-lg">Sign up as a user and click "Manage My Listings" to create a produce listing. Upload a photo of your produce, add a description of your donation, and specify pick-up location/contact details in your listing.
		</li>
		<li class="faq-question header-text-sm">
		Can I create a "produce wanted" listing?
		</li>
		<li class="faq-answer instructional-text-lg">As of right now users can only create listings for produce they want to donate. They cannot create listings asking for produce donations.
		</li>
		<li class="faq-question header-text-sm">
		What will my produce cost? How much money can I expect to make by listing my available produce?
		</li>
		<li class="faq-answer instructional-text-lg">SiteName just connects produce suppliers with interested parties. Our hope is that listing owners will not charge money for their donations, and in return, interested parties will pick up produce to help offset owner waste-management costs. 
		</li>
		<li class="faq-question header-text-sm">
		How do I get in contact with someone about their listing?
		</li>
		<li class="faq-answer instructional-text-lg">Navigate to a listing's page to see the owner's contact details and their preferred method of contact!
		</li>
		<li class="faq-question header-text-sm">
		How do I know where to pick up my produce? Can I have it delivered?
		</li>
		<li class="faq-answer instructional-text-lg">
		Contact the owner of the listing you're interested in to negotiate pick-up/delivery details.
		</li>
		<li class="faq-question header-text-sm">
		Can I create a listing for produce that isn't "imperfect"? Can I create a listing for spoiled produce (so it may be used for compost)?
		</li>
		<li class="faq-answer instructional-text-lg">Any and all produce donations are appreciated! If you are listing older or spoiled produce, please explicitly label it as compost materials in your listing title.
		</li>
		<li class="faq-question header-text-sm">Where can I learn more about produce waste?</li>
		<li class="faq-answer instructional-text-lg">
			<ul id="faq-links-ul">
				<li>
				<a href="http://www.nytimes.com/2015/11/24/us/getting-ugly-produce-onto-tables-so-they-stay-out-of-trash.html?_r=0" class="faq-link">NYT-Getting Ugly Produce Onto Tables So It Stays Out of Trash</a>
				</li>
				<li>
				<a href="https://www.nrdc.org/food/files/wasted-food-ip.pdf" class="faq-link">Wasted: How America Is Losing Up to 40
				Percent of Its Food from Farm to Fork to Landfill</a>
				</li>
				<li>
				<a href="https://www.change.org/p/whole-foods-and-walmart-stop-contributing-to-massive-food-waste-in-the-us-48d63891-457f-4496-98d7-8b6daa1ee125?recruiter=341562939&utm_campaign=signature_receipt&utm_medium=email&utm_source=share_petition" class="faq-link">What the Fork Are You Doing With Your Produce, Walmart and Whole Foods?</a>
				</li>
				<li>
				<a href="http://www.worldfooddayusa.org/food_waste_the_facts" class="faq-link">Food Waste: The Facts</a>
				</li>
				<li>
				<a href="http://www.imperfectproduce.com/#home" class="faq-link">Imperfect Produce--Ugly Produce. Delivered.</a>
				</li>
				<li>
				<a href="https://www.instagram.com/uglyfruitandveg/?hl=en" class="faq-link">The UglyFruitAndVeg Instagram Feed</a>
				</li>
				<li>
				<a href="http://www.endfoodwaste.org/ugly-fruit---veg.html" class="faq-link">EndFoodWaste.org</a>
				</li>
			</ul>
		</li>
	</ul>
</div>
<%= image_tag "rowfruit2.png", :class => "bottom-row-image" %>
<!-- <img src="/assets/rowfruit2.png" class="bottom-row-image"> -->

app/views/home/home.html.erb
<div id="jumbo-image-div">
	<div id="homepage-text">
		<h1 class="jumbo-header"><b>Love at First Bite</b></h1>
		<p class="jumbo-subheader">getting ugly produce onto hungry people's plates.</p>
		<% if current_user %>
			<%= button_to "Browse Produce", "/search", method: "get", class: "btn btn-default btn-lg", id: "lemon-button"%>
		<% else %>
			<%= button_to "Sign Up", "/users/new", method: "get", class: "btn btn-default btn-lg", id: "lemon-button" %>
		<% end %>
	</div>
	<%= image_tag "uglylemon.png", :id => "jumbo-image" %>
<!-- 	<img src="/assets/uglylemon.png" id="jumbo-image">
 --></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Love At First Bite</title>
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Font+Name">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if current_user %>
		<%= render "loggedin_navbar" %>
	<% else %>
		<%= render "loggedout_navbar" %>
	<% end %>
<%= yield %>
</body>
</html>

app/views/layouts/loggedout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProduceProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
	<%= render "loggedout_navbar" %>

<%= yield %>

</body>
</html>

app/views/layouts/search_listings.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Love At First Bite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Font+Name">
<script charset="utf-8" src="//ucarecdn.com/widget/2.6.0/uploadcare/uploadcare.full.min.js"></script>
</head>
<body>
<div class="container-fluid">
	<%= render "loggedin_navbar" %>
	<%= render "sidebar" %>
	
<%= yield %>
</div>
</body>
</html>

app/views/listings/edit.html.erb
<div class="listing-form-div">
<span class="header-text-md">Edit Listing</span>
<br>
<div class="instructional-text-sm" style="color: red"><i>* field is required</i></div>
<br>
<%= form_for @listing do |f| %>
   <%= f.hidden_field :user_id, value: @current_user.id %>
  <div class="form-group">
    <div class="instructional-text-md">Title<span class="instructional-text-sm" style="color: red">*</span></div>
    <%= f.text_field :title, required: true %>
  </div>
  <div class="form-group"> 
    <span class="instructional-text-md">Produce Category<span class="instructional-text-sm" style="color: red">*</span></span>
    <%= f.select :produce_category, Listing.produce_categories, required: true %>
  <br>
  <br>
  <div class="form-group">  
    <div class="instructional-text-md">Quantity<span class="instructional-text-sm" style="color: red">*</span></div>
    <%= f.text_area :quantity, placeholder: "How much produce would you like to donate? ex. 7 pints of strawberries, one dozen bell peppers, 20lb case fingerling potatoes",required: true %>
  </div>
  <div class="form-group">
    <div class="instructional-text-md">Description</div>
    <%= f.text_area :description, placeholder: "Include a brief description of produce donation here" %>
  </div>
  <div class="form-group">
    <div class="instructional-text-md">Upload a photo of your produce! (optional)</div>
    <br>
    <%= f.file_field :avatar %>
    <br>
  </div>
<div class="header-text-sm">Pick-up Details</div>
<div class="instructional-text-md">Let users know where they will be picking up!</div>
<br>
  <div class="form-group">
    <div class="instructional-text-md">Address</div>
  <%= f.text_field :address_line1 %>
  </div>
  <div class="form-group">
  <%= f.text_field :address_line2 %>
  </div>
  <div class="form-group">
    <div class="instructional-text-md">City<span class="instructional-text-sm" style="color: red">*</span></div>
  <%= f.text_field :city, required: true %>
  </div>
  <div class="form-group">
    <div class="instructional-text-md">State</div>
  <%= f.text_field :state %>
  </div>
  <div class="form-group">
    <div class="instructional-text-md">Zip Code</div>
  <%= f.text_field :zip %>
  </div>
  <div class="form-group">
    <div class="instructional-text-md">Phone Number</div>
  <%= f.text_field :phone %>
  </div>
  <div class="instructional-text-md">How do you want users to contact you?</div>
  <br>
    <div class="form-group">
    <span class="instructional-text-md">Prefer Phone</span>
  <%= f.check_box :prefers_phone %>
  </div>
    <div class="form-group">
    <span class="instructional-text-md">Prefer Email</span>
  <%= f.check_box :prefers_email %>
  </div>
  <%= f.submit "Save Changes", class: "btn btn-default", id: "edit-listing-button" %>
<% end %> 
<br>
<br>
<% if @listing.persisted? %>
    <%= button_to "Delete Listing", "/listings/#{@listing.id}", method: "delete", confirm: "Are you sure you want to delete this listing?", class: "btn btn-default", id:"delete-listing-button" %>
<% end %>
</div>

app/views/listings/index.html.erb
<% @listings.each do |listing| %>
<%= listing.title %>
<%= listing.description %>
<% end %>

app/views/listings/mylistings.html.erb
<div id="mylistings-div">
<div id="button-div">
	<%= button_to "Add New Listing", "/listings/new", method: "get", class: "btn btn-default", id:"add-listing-button"%>
<br>
</div>
<br>
<div class="all-of-mylistings-div col-md-offset-2 col-md-10">
	<% @current_user.listings.each do |listing| %>
		<div class="mylistings-listing-details">
			<div class="mylistings-listing-pic">
				<%= image_tag(listing.avatar.url(:medium)) %>
			</div>

			<div class="mylistings-listing-details-text">
				<h3 class="header-text-md">
					<%= link_to listing.title, "/listings/#{listing.id}", class: "listing-details-text" %>
				</h3>
				<p class="instructional-text-sm">Listing created <%= time_ago_in_words(listing.created_at.in_time_zone('Eastern Time (US & Canada)')) %> ago</p>
				<p class="instructional-text-md">Quantity: <%= listing.quantity %></p>
				<p class="instructional-text-md">Description: <%= listing.description %></p>
				<div class="mylistings-edit-buttons">
					<%= button_to "Edit Listing", "/listings/#{listing.id}/edit", method: "get", class: "btn btn-default" %>
				</div>
			</div>

		</div>
	<% end %>
</div>

app/views/listings/new.html.erb
<div class="listing-form-div">
<span class="header-text-md">Create a new listing</span>
<br>
<div class="instructional-text-sm" style="color: red"><i>* field is required</i></div>
<br>
<%= form_for @listing do |f| %>
  <%= f.hidden_field :user_id, value: @current_user.id %>
  <div class="form-group">
  	<div class="instructional-text-md">Title<span class="instructional-text-sm" style="color: red">*</span></div>
    <%= f.text_field :title, required: true %>
  </div>
  <div class="form-group"> 
    <span class="instructional-text-md">Produce Category<span class="instructional-text-sm" style="color: red">*</span></span>
    <%= f.select :produce_category, Listing.produce_categories, required: true %>
  <br>
  <br>
  <div class="form-group"> 	
  	<div class="instructional-text-md">Quantity<span class="instructional-text-sm" style="color: red">*</span></div>
    <%= f.text_area :quantity, placeholder: "How much produce would you like to donate? ex. 7 pints of strawberries, one dozen bell peppers, 20lb case fingerling potatoes",required: true %>
  </div>
  <div class="form-group">
  	<div class="instructional-text-md">Description</div>
    <%= f.text_area :description, placeholder: "Include a brief description of produce donation here" %>
  </div>
  <div class="form-group">
    <div class="instructional-text-md">Upload a photo of your produce! (optional)</div>
    <br>
    <%= f.file_field :avatar %>
    <br>
  </div>
<div class="header-text-sm">Pick-up Details</div>
<div class="instructional-text-md">Let users know where they will be picking up!</div>
<br>
  <div class="form-group">
   	<div class="instructional-text-md">Address</div>
	<%= f.text_field :address_line1 %>
  </div>
  <div class="form-group">
  <%= f.text_field :address_line2 %>
  </div>
  <div class="form-group">
    <div class="instructional-text-md">City<span class="instructional-text-sm" style="color: red">*</span></div>
  <%= f.text_field :city, required: true %>
  </div>
  <div class="form-group">
    <div class="instructional-text-md">State</div>
  <%= f.text_field :state %>
  </div>
  <div class="form-group">
    <div class="instructional-text-md">Zip Code</div>
  <%= f.text_field :zip %>
  </div>
  <div class="form-group">
    <div class="instructional-text-md">Phone Number</div>
  <%= f.text_field :phone %>
  </div>
  <div class="instructional-text-md">How do you want users to contact you?</div>
  <br>
    <div class="form-group">
    <span class="instructional-text-md">Prefer Phone</span>
  <%= f.check_box :prefers_phone %>
  </div>
    <div class="form-group">
    <span class="instructional-text-md">Prefer Email</span>
  <%= f.check_box :prefers_email %>
  </div>
  <%= f.submit "Create Listing", class: "btn btn-default", id:"create-listing-button" %>
<% end %> 
</div>

app/views/listings/search.html.erb
<h1>sanity check: this is where we search for fruit</h1>

app/views/users/index.html.erb
<% @users.each do |user| %>
<%= user.username %>
<%= user.email %>
<% end %>

app/views/users/show.html.erb
<div class="user-profile col-md-8 col-md-offset-2">
	<div class="profile-details">
		<div class="profile-pic">
			<%= image_tag(@user.avatar.url(:medium)) %>
		</div>
		<div class="profile-details-text">
			<h2 class="header-text-lg"><b>
				<%= @user.username %></b>
			</h2>
			<p class="header-text-sm">
				Email: <%= @user.email %>
			</p>
			<% if current_user == @user %>
				<div class="left-button">
					<%= button_to "Edit My Profile", edit_user_path(@user), method: "get", class: "btn btn-default button-pair" %>
				</div>
				<div class="right-button">
					<%= button_to "Manage My Listings", "/listings/mylistings", method: "get", class: "btn btn-default button-pair"  %>
				</div>
			<% end %>
		</div>
	</div>

	<div class="listings-details">
		<% if @user.listings.count > 0 %> 
			<h3 class="header-text-md"><b>View <%= @user.username %>'s listings:</b></h3>
			<% @user.listings.each do |listing| %>
			<div class="listing-details-text">
				<h3 class="header-text-sm"><%= link_to listing.title, "/listings/#{listing.id}" %></h3>
				<p class="instructional-text-sm">Listing created <%= time_ago_in_words(listing.created_at.in_time_zone('Eastern Time (US & Canada)')) %> ago</p>
				<p class="instructional-text-md">Quantity: <%= listing.quantity %></p>
				<p class="instructional-text-md">Description: <%= listing.description %></p>
			</div>
			<div class="listing-image">
				<%= link_to image_tag(listing.avatar.url(:medium)), "/listings/#{listing.id}", class: "listing-image" %>
			</div>
			<% end %>
		<% else %>
			<h3><%= @user.username %> doesn't have any listings yet!</h3>
		<% end %>
	</div>
</div>